spring.application.name=ogumap

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/ogudb_schema
spring.datasource.username=root
spring.datasource.password=35944649Ab$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# データベース初期化設定
spring.sql.init.encoding=utf-8
# データベース初期化を常に有効にする
spring.sql.init.mode=never
# always

# データの読み込みとスキーマの場所を指定する（任意）
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.schema-locations=classpath:schema.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE