---- members テーブル（会員共通情報）
--CREATE TABLE IF NOT EXISTS members (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    username VARCHAR(50) NOT NULL UNIQUE,
--    email VARCHAR(100) NOT NULL UNIQUE,
--    password VARCHAR(255) NOT NULL,
--    type ENUM('admin', 'shop', 'company') NOT NULL,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
--);
--
---- shops テーブル（店舗情報）の作成
--CREATE TABLE IF NOT EXISTS shops (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    member_id INT NOT NULL,
--    shop_name VARCHAR(100) NOT NULL,
--    address VARCHAR(255) NOT NULL,
--    category1 VARCHAR(100) NOT NULL,
--    category2_1 VARCHAR(100) NOT NULL,
--    category2_2 VARCHAR(100),
--    latitude DECIMAL(9,6),
--    longitude DECIMAL(9,6),
--    phone_number VARCHAR(20),
--    website VARCHAR(100),
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
--);
--
---- companies テーブル（会社情報）
--CREATE TABLE IF NOT EXISTS companies (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    member_id INT NOT NULL,
--    company_name VARCHAR(100) NOT NULL,
--    address VARCHAR(255) NOT NULL,
--    latitude DECIMAL(9,6),
--    longitude DECIMAL(9,6),
--    contact_email VARCHAR(100),
--    phone_number VARCHAR(20),
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
--);
--
---- roles テーブル（権限情報）
--CREATE TABLE IF NOT EXISTS roles (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(50) NOT NULL
--);
--
---- member_roles テーブル（会員と権限の中間テーブル）
--CREATE TABLE IF NOT EXISTS member_roles (
--    member_id INT NOT NULL,
--    role_id INT NOT NULL,
--    PRIMARY KEY (member_id, role_id),
--    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
--    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
--);
--
---- posts テーブル（サイト内投稿情報）
--CREATE TABLE IF NOT EXISTS posts (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    member_id INT NOT NULL,
--    shop_id INT,
--    content TEXT NOT NULL,
--    image_url VARCHAR(255),
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
--    FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE SET NULL
--);
--
---- external_posts テーブル（外部APIからの投稿情報）
--CREATE TABLE IF NOT EXISTS external_posts (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    platform ENUM('X', 'Instagram') NOT NULL,
--    external_id VARCHAR(100) NOT NULL UNIQUE,
--    member_id INT,
--    content TEXT,
--    media_url VARCHAR(255),
--    posted_at TIMESTAMP NOT NULL,
--    retrieved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL
--);
--
---- 権限データの初期データを挿入
--INSERT INTO roles (name) VALUES ('ROLE_ADMIN'), ('ROLE_SHOP'), ('ROLE_COMPANY');